server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
  register-with-eureka: false  # 🔒 Este servidor **no se registra** a sí mismo en Eureka.
  fetch-registry: false        # 📦 Este servidor **no descarga el registro** de otros servicios.
